# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=registry.redhat.io/rhel9/python-312:9.8-1790171739@sha256:8b1b36418501692d863a68f7f31ae47f1f169b83f7cdcc84831ac002304af693
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-baseline-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.6
